import fs from 'node:fs';
import { fileURLToPath } from 'node:url';
import { encodeLayout, color565 } from '../dist/device-codec.mjs';
const root = new URL('../', import.meta.url);
const config = JSON.parse(fs.readFileSync(new URL('dist/defaults.json', root)));
const font = JSON.parse(fs.readFileSync(new URL('dist/font.json', root)));
const hex = n => `0x${n.toString(16).padStart(4, '0')}`;
let offline = '#pragma once\n#include <cstdint>\n#include <cstring>\n// Generated by scripts/generate_device_assets.mjs from dist/defaults.json.\n';
for (const [code, logo] of Object.entries(config.logos)) {
  const palette = ['#000000', ...new Set(logo.pixels.filter(c => c !== '#000000'))];
  if (logo.width !== 28 || logo.height !== 28 || palette.length > 4 || palette.includes(null))
    throw new Error(`Offline demo requires opaque 28x28, four-color logos: ${code}`);
  offline += `static const uint16_t PALETTE_${code}[] = {${palette.map(c => hex(color565(c))).join(', ')}};\n`;
  offline += `static const uint64_t LOGO_${code}[28] = {\n`;
  for (let y = 0; y < 28; y++) {
    let row = 0n;
    for (let x = 0; x < 28; x++) row |= BigInt(palette.indexOf(logo.pixels[y*28+x])) << BigInt(x*2);
    offline += `  0x${row.toString(16).padStart(16,'0')}ULL,\n`;
  }
  offline += '};\n';
}
offline += 'inline uint16_t logoColor(const char* airline, uint8_t index) {\n';
for (const code of Object.keys(config.logos))
  offline += `  if (!std::strcmp(airline, "${code}")) return index < sizeof(PALETTE_${code})/sizeof(uint16_t) ? PALETTE_${code}[index] : 0;\n`;
offline += '  return 0xffff;\n}\n';
for (const [name, field] of [['Aircraft', 'aircraft'], ['Plane', 'progress']])
  offline += `static const uint16_t kDemo${name}Color = ${hex(color565(config.layout.elements.find(e => e.field === field).color))};\n`;
const outputs = {
  'firmware/include/offline_logo_data.h': offline,
  'firmware/include/default_layout.h': `#pragma once\n#include <cstdint>\n// Generated by scripts/generate_device_assets.mjs.\nstatic const uint8_t kDefaultLayout[] = {\n${Array.from(encodeLayout(config)).map((n,i) => (i % 24 === 0 ? '\n  ' : '') + n).join(',')}\n};\n`,
  'firmware/include/font_data.h': `#pragma once\n#include <cstdint>\nnamespace flightdeck {\nstatic const uint16_t kGlyphs[128] = {${Array.from({length:128},(_,i)=>parseInt((font[String.fromCharCode(i)] || ['000','000','000','000','000']).join(''),2)).join(',')}};\n}\n`,
};
for (const [file, content] of Object.entries(outputs)) {
  const path = fileURLToPath(new URL(file, root));
  if (process.argv.includes('--check')) { if (fs.readFileSync(path,'utf8') !== content) throw new Error(`Regenerate ${file}`); }
  else fs.writeFileSync(path, content);
}
