import fs from 'node:fs';
import { fileURLToPath } from 'node:url';
import { encodeLayout } from '../dist/device-codec.mjs';
const root = new URL('../', import.meta.url);
const config = JSON.parse(fs.readFileSync(new URL('dist/defaults.json', root)));
const font = JSON.parse(fs.readFileSync(new URL('dist/font.json', root)));
const outputs = {
  'firmware/include/default_layout.h': `#pragma once\n#include <cstdint>\n// Generated by scripts/generate_device_assets.mjs.\nstatic const uint8_t kDefaultLayout[] = {\n${Array.from(encodeLayout(config)).map((n,i) => (i % 24 === 0 ? '\n  ' : '') + n).join(',')}\n};\n`,
  'firmware/include/font_data.h': `#pragma once\n#include <cstdint>\nnamespace flightdeck {\nstatic const uint16_t kGlyphs[128] = {${Array.from({length:128},(_,i)=>parseInt((font[String.fromCharCode(i)] || ['000','000','000','000','000']).join(''),2)).join(',')}};\n}\n`,
};
for (const [file, content] of Object.entries(outputs)) {
  const path = fileURLToPath(new URL(file, root));
  if (process.argv.includes('--check')) { if (fs.readFileSync(path,'utf8') !== content) throw new Error(`Regenerate ${file}`); }
  else fs.writeFileSync(path, content);
}
